### ISSUE TITLE
[Issue] white screen when clicking GENERATE

### ISSUE THREAD

**Issue by orliesaurus** [FlowTestAI/FlowTest#86] opened 2024-04-25 19:00 UTC
Hi, I was testing the application: great job so far I really love it.

I encountered a stopping bug that occurred when I tried to click the generate button.

please find attached a dash of the bug

[![white window busted](https://replayable-api-production.herokuapp.com/replay/662a98997f1976007096b93b/gif?shareKey=7dFzyjGPaHuiBP2YDNjHag)](https://app.dashcam.io/replay/662a98997f1976007096b93b?share=7dFzyjGPaHuiBP2YDNjHag)

```
Flowtest shows a white window and forces me to force close
```

Watch [white window flowtest](https://app.dashcam.io/replay/662a98997f1976007096b93b?share=7dFzyjGPaHuiBP2YDNjHag) on Dashcam

**Comment by jsajal** [comment] 2024-04-26 02:37
thanks for reporting this. 
I was able to reproduce this, looks like we didn't do proper safeguarding in case the OPENAI key is not added.

To over come this bug, one can do step 6 listed in https://flowtestai.gitbook.io/flowtestai/generative-ai , then selecting the model won't give a white screen

**Comment by jsajal** [comment] 2024-05-07 02:54
fixed in https://github.com/FlowTestAI/FlowTest/commit/c7011592d408440c717173bc3b01bb79f74f27d3

**Closed by jsajal** 2024-05-07 02:54 UTC
